name: media_share_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  riverpod: ^2.4.1
  flutter_riverpod: ^2.4.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  shared_preferences: ^2.2.1
  rive: ^0.11.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/rive/


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway.ttf
        
